# Build the module.
steps: 
- name: 'docker.io/hashicorp/terraform:0.12.26'
  id: 'plan-sandbox'
  entrypoint: /bin/bash
  args: 
    - 'terraform init'
    - 'terraform validate'
    - 'terraform plan'
  dir: 'environments/sandbox'