# Build the module.
steps: 
 - name: 'docker.io/hashicorp/terraform:0.12.26'
   id: 'terraform-init'
   args: 
    - 'init'
   dir: "environments/$BRANCH_NAME"
 - name: 'docker.io/hashicorp/terraform:0.12.26'
   id: 'terraform-validate'
   args: 
    - 'validate'
   dir: "environments/$BRANCH_NAME"
 - name: 'docker.io/hashicorp/terraform:0.12.26'
   id: 'terraform-plan'
   args: 
    - 'plan'
   dir: "environments/$BRANCH_NAME"
 - name: 'docker.io/hashicorp/terraform:0.12.26'
   id: 'terraform-apply'
   args: 
    - 'apply'
    - '--auto-approve'
   dir: "environments/$BRANCH_NAME"
   waitFor: ['terraform-plan']
