steps:
  - name: docker.io/hashicorp/terraform:0.12.26
    id: terraform-init
    args:
      - "init"
    dir: "environments/$BRANCH_NAME"
  - name: docker.io/hashicorp/terraform:0.12.26
    id: terraform-validate
    args:
      - "validate"
    dir: "environments/$BRANCH_NAME"
    waitFor: [terraform-init]
  - name: docker.io/hashicorp/terraform:0.12.26
    id: terraform-plan
    args:
      - "plan"
    dir: "environments/$BRANCH_NAME"
    waitFor: [terraform-validate]
  - name: docker.io/hashicorp/terraform:0.12.26
    id: terraform-apply
    args:
      - "apply"
      - "--auto-approve"
    dir: "environments/$BRANCH_NAME"
    waitFor: [terraform-plan]

  - name: docker.io/chef/inspec:4.20.2
    id: inspec-test
    args: ["exec", ".", "--target", "gcp://", "--input-file", "attributes.yml"]
    dir: inspec-profile
    env:
      - "CHEF_LICENSE=accept"
