# Build the module.
steps: 
- name: 'docker.io/bash:latest'
  id: 'plan-sandbox'
  args: 
    - 'echo this'
    # - 'terraform init'
    # - 'terraform validate'
    # - 'terraform plan'
  dir: 'environments/sandbox'