# Build the module.
steps: 
 - name: 'docker.io/hashicorp/terraform:0.12.26'
   id: 'init-sandbox'
   args: 
    - 'init'
   dir: 'environments/sandbox'
 - name: 'docker.io/hashicorp/terraform:0.12.26'
   id: 'validate-sandbox'
   args: 
    - 'validate'
   dir: 'environments/sandbox'
 - name: 'docker.io/hashicorp/terraform:0.12.26'
   id: 'plan-sandbox'
   args: 
    - 'plan'
   dir: 'environments/sandbox'
 - name: 'docker.io/hashicorp/terraform:0.12.26'
   id: 'apply-sandbox'
   args: 
    - 'apply'
    - '--auto-approve'
   dir: 'environments/sandbox'