# Build the module.
steps: 
 - name: 'docker.io/hashicorp/terraform:0.12.26'
   id: 'init-sandbox'
   args: 
    - 'terraform init'
   dir: 'environments/sandbox'
 - name: 'docker.io/hashicorp/terraform:0.12.26'
   id: 'validate-sandbox'
   args: 
    - 'terraform validate'
   dir: 'environments/sandbox'