# Build the module.
steps: 'docker.io/hashicorp/terraform:0.12.26'
 - name: 
   id: terraform-init
   args: 
    - 'init'
   dir: "environments/$BRANCH_NAME"
 - name: 
   id: terraform-validate
   args: 
    - 'validate'
   dir: "environments/$BRANCH_NAME"
 - name:
   id: terraform-plan
   args: 
    - 'plan'
   dir: "environments/$BRANCH_NAME"
 - name: 
   id: terraform-apply
   args: 
    - 'apply'
    - '--auto-approve'
   dir: "environments/$BRANCH_NAME"
   waitFor: [terraform-plan]
